version: "3.9"
services:
  db:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: my-python-app
    depends_on:
      - db
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork: